name: Test Astral uv cache

on:
  workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
    - run: find /home/runner | grep uv
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
    - run: find /home/runner | grep uv
    - name: Cowsay
      run: uvx cowsay -t "I hope this is cached"
    - run: find /home/runner | grep uv
